export enum Subject {
  mathematics = 'mathematics',
  physics = 'physics',
  informationTechnology = 'informationTechnology',
  biology = 'biology',
  ethics = 'ethics',
  history = 'history',
  chemistry = 'chemistry',
  art = 'art',
  geography = 'geography',
  handicraft = 'handicraft',
  pe = 'pe',
  music = 'music',
  religion = 'religion',
  finnishLanguage = 'finnishLanguage',
  russianLanguage = 'russianLanguage',
  englishLanguage = 'englishLanguage',
  finnishForForeigners = 'finnishForForeigners',
  spanishLanguage = 'spanishLanguage',
  swedishLanguage = 'swedishLanguage',
  socialStudies = 'socialStudies',
  healthEducation = 'healthEducation',
  homeEconomics = 'homeEconomics',
  studentGuidance = 'studentGuidance',
}
